# Smart Helmet AI - Member 1
## Dataset Analysis and Data Preprocessing

In [1]:
import sys
print(sys.executable)

c:\Users\RAVI\Desktop\smart_helmet_ai\venv\Scripts\python.exe

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Scikit-learn version:", sklearn.__version__)
print("All required libraries are working!")

Pandas version: 3.0.5
NumPy version: 2.5.2
Scikit-learn version: 1.9.0
All required libraries are working!

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Number of samples
normal_samples = 500
accident_samples = 500

# -----------------------------
# NORMAL SENSOR DATA
# -----------------------------

normal_data = pd.DataFrame({
    "timestamp": np.arange(normal_samples),

    "accel_x": np.random.normal(0, 0.5, normal_samples),
    "accel_y": np.random.normal(0, 0.5, normal_samples),
    "accel_z": np.random.normal(9.8, 0.5, normal_samples),

    "gyro_x": np.random.normal(0, 5, normal_samples),
    "gyro_y": np.random.normal(0, 5, normal_samples),
    "gyro_z": np.random.normal(0, 5, normal_samples),

    "label": "Normal"
})


# -----------------------------
# ACCIDENT-LIKE SENSOR DATA
# -----------------------------

accident_data = pd.DataFrame({
    "timestamp": np.arange(normal_samples,
                            normal_samples + accident_samples),

    "accel_x": np.random.normal(0, 3, accident_samples),
    "accel_y": np.random.normal(0, 3, accident_samples),
    "accel_z": np.random.normal(12, 3, accident_samples),

    "gyro_x": np.random.normal(0, 80, accident_samples),
    "gyro_y": np.random.normal(0, 80, accident_samples),
    "gyro_z": np.random.normal(0, 80, accident_samples),

    "label": "Accident"
})


# Combine both classes
dataset = pd.concat(
    [normal_data, accident_data],
    ignore_index=True
)

# Shuffle the dataset
dataset = dataset.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# Display first 10 rows
dataset.head(10)

,timestamp,accel_x,accel_y,accel_z,gyro_x,gyro_y,gyro_z,label
0,521,-1.389484,-7.479812,7.728952,85.946640,-58.809344,-52.923315,Accident
1,737,-3.764768,-0.478087,10.958093,2.720648,96.206120,112.962150,Accident
2,740,0.037498,-2.144042,6.474307,41.509694,-8.159577,27.068595,Accident
3,660,-1.819510,-1.080118,12.038486,118.556861,21.840857,-4.382269,Accident
4,411,-0.562321,0.109575,10.078115,11.156501,7.689660,1.792268,Normal
5,678,2.925937,3.575122,17.440223,68.914922,-9.990951,28.779118,Accident
6,626,-5.728068,-2.502969,9.357738,-53.375127,-21.898340,26.224886,Accident
7,513,-4.191355,-5.242910,12.596040,-74.847704,-19.014665,20.701584,Accident
8,859,-2.939164,-0.586171,14.040661,-11.322060,-21.987624,-50.514962,Accident
9,136,-0.391627,0.411585,10.394735,-4.775613,0.509281,0.953178,Normal

In [2]:
dataset["label"].value_counts()

label
Accident    500
Normal      500
Name: count, dtype: int64

In [3]:
print("Number of rows:", dataset.shape[0])
print("Number of columns:", dataset.shape[1])

Number of rows: 1000
Number of columns: 8

In [4]:
dataset.to_csv(
    "../dataset/raw/smart_helmet_sensor_data.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
data_path = "../dataset/raw/smart_helmet_sensor_data.csv"

df = pd.read_csv(data_path)

df.head()

,timestamp,accel_x,accel_y,accel_z,gyro_x,gyro_y,gyro_z,label
0,521,-1.389484,-7.479812,7.728952,85.946640,-58.809344,-52.923315,Accident
1,737,-3.764768,-0.478087,10.958093,2.720648,96.206120,112.962150,Accident
2,740,0.037498,-2.144042,6.474307,41.509694,-8.159577,27.068595,Accident
3,660,-1.819510,-1.080118,12.038486,118.556861,21.840857,-4.382269,Accident
4,411,-0.562321,0.109575,10.078115,11.156501,7.689660,1.792268,Normal

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 1000
Number of columns: 8

In [4]:
print(df.columns.tolist())

['timestamp', 'accel_x', 'accel_y', 'accel_z', 'gyro_x', 'gyro_y', 'gyro_z', 'label']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  1000 non-null   int64
 1   accel_x    1000 non-null   float64
 2   accel_y    1000 non-null   float64
 3   accel_z    1000 non-null   float64
 4   gyro_x     1000 non-null   float64
 5   gyro_y     1000 non-null   float64
 6   gyro_z     1000 non-null   float64
 7   label      1000 non-null   str
dtypes: float64(6), int64(1), str(1)
memory usage: 62.6 KB

In [6]:
print(df.isnull().sum())

timestamp    0
accel_x      0
accel_y      0
accel_z      0
gyro_x       0
gyro_y       0
gyro_z       0
label        0
dtype: int64

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [8]:
print(df["label"].value_counts())

label
Accident    500
Normal      500
Name: count, dtype: int64

In [9]:
print(df["label"].unique())

<StringArray>
['Accident', 'Normal']
Length: 2, dtype: str

In [10]:
df.describe()

,timestamp,accel_x,accel_y,accel_z,gyro_x,gyro_y,gyro_z
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,499.500000,-0.026080,-0.020412,10.786070,-0.097568,-1.343162,-2.366675
std,288.819436,2.228988,2.183688,2.327437,56.203295,54.945781,59.217016
min,0.000000,-8.788346,-7.479812,2.977103,-254.136305,-190.744543,-231.961110
25%,249.750000,-0.690388,-0.641406,9.534864,-8.077133,-9.366543,-9.586768
50%,499.500000,0.003869,0.014625,10.120210,-0.044567,-0.333277,-0.205327
75%,749.250000,0.677232,0.712704,11.838651,8.712246,7.030498,7.689079
max,999.000000,8.605209,9.729279,20.443963,249.032816,234.852632,247.863955

In [13]:
df = pd.read_csv("../dataset/raw/smart_helmet_sensor_data.csv")

In [14]:
print(df["label"].unique())
print(df["label"].value_counts(dropna=False))

<StringArray>
['Accident', 'Normal']
Length: 2, dtype: str
label
Accident    500
Normal      500
Name: count, dtype: int64

In [15]:
df["label"] = df["label"].map({
    "Normal": 0,
    "Accident": 1
})

print(df["label"].value_counts())

label
1    500
0    500
Name: count, dtype: int64

In [16]:
print(df["label"].unique())

[1 0]

In [17]:
X = df.drop("label", axis=1)
y = df["label"]

print("Features:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

Features:
['timestamp', 'accel_x', 'accel_y', 'accel_z', 'gyro_x', 'gyro_y', 'gyro_z']

Target:
label

In [18]:
print(X.dtypes)

timestamp      int64
accel_x      float64
accel_y      float64
accel_z      float64
gyro_x       float64
gyro_y       float64
gyro_z       float64
dtype: object

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 800
Testing samples: 200

In [20]:
print("Training label distribution:")
print(y_train.value_counts())

print("\nTesting label distribution:")
print(y_test.value_counts())

Training label distribution:
label
1    400
0    400
Name: count, dtype: int64

Testing label distribution:
label
1    100
0    100
Name: count, dtype: int64

In [21]:
X = X.drop("timestamp", axis=1)

print(X.columns.tolist())

['accel_x', 'accel_y', 'accel_z', 'gyro_x', 'gyro_y', 'gyro_z']

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 800
Testing samples: 200

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training data shape:", X_train_scaled.shape)
print("Scaled testing data shape:", X_test_scaled.shape)

Scaled training data shape: (800, 6)
Scaled testing data shape: (200, 6)

In [24]:
print("First 5 scaled training rows:")
print(X_train_scaled[:5])

First 5 scaled training rows:
[[-1.35457717  0.53355908  0.94176563 -1.73762503  1.05682479 -1.33834703]
 [ 0.08066759  0.18533856 -0.61622683  0.26748983 -0.13280123  0.11456481]
 [ 2.14390684 -3.25035742  1.38158399 -1.02366366 -0.75978139 -2.07076876]
 [-0.32420977  0.21833771 -0.46353866  0.09216676 -0.05616425 -0.07916333]
 [ 1.87274906 -1.41259231  1.86173661 -3.18847283  1.58615421  0.70145772]]